name: Generate Consent Management API Docs

on:
  # Automatically trigger when push model/package config changes to main branch
  push:
    branches: ["main"]
    paths:
      - '**.json'
      - '**.kts'
      - '**.yaml'
      - 'models/**'
      - 'gradle.properties'
  # Enable running workflow manually from GitHub Actions
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate-api-docs:
    name: Generate API Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Generate API docs and deploy to GitHub Pages
        uses: msayson/openapi-github-pages-action@v2.0.0
        with:
          api-configs: |-
            [
              {
                "openapi-json-filepath": "openapi/ConsentManagementApi.openapi.json",
                "api-doc-filepath": "v1/docs.html"
              }
            ]
          api-docs-dir: docs
